---
title: "tidy_tuesday"
author: "Brian"
date: "3/9/2021"
output: html_document
---

#loading libraries
```{r}
library(ggplot2) #generating visualizations
library(dplyr) #data manipulation
library(tidyr) #data shaping
library(readxl) #read excel files

```


#loading dataset
```{r}
supermarket<-read_excel("./Supermarket Transactions.xlsx", sheet = "Data")

#explore the dataset
head(supermarket)
```
#data manipulation
```{r}
city_rev<-supermarket %>% group_by(City) %>% 
          summarise(Revenue = sum(Revenue, na.rm = TRUE)) %>% arrange(Revenue) %>%
            mutate(City=factor(City, levels = .$City))
head(city_rev)
```

#plotting
```{r}
ggplot(data = city_rev,aes(y=Revenue, x=reorder(City,Revenue)))+
  geom_bar(stat = "identity")+
  labs(
    x="City"
  )+
  coord_flip()
```

#grouping by gender
```{r}
city_gender<-supermarket %>% group_by(City,Gender) %>% 
          summarise(Revenue = sum(Revenue, na.rm = TRUE)) %>% ungroup() %>%
          mutate(City=factor(City, levels =city_rev$City ))
head(city_gender)
```
#labels
```{r}
right_label<-city_gender %>% group_by(City) %>%
              arrange(desc(Revenue)) %>% top_n(1)

left_label<-city_gender %>% group_by(City) %>%
              arrange(desc(Revenue)) %>% slice(2)
head(left_label)
```


#cleveland plot
```{r}
ggplot(data = city_gender,aes(x=Revenue,y=City))+
  geom_line(aes(group=City))+
  geom_point(aes(color=Gender),size=1.5)+
  geom_text(data = right_label,aes(color=Gender,label=round(Revenue,0)),size=3,hjust=-.5)+
  geom_text(data = left_label,aes(color=Gender,label=round(Revenue,0)),size=3,hjust=1.5)+
  scale_x_continuous(limits = c(-500,10500))
```
#creating big diff
```{r}
big_diff <- city_gender %>% spread(Gender,Revenue) %>% group_by(City) %>%
            mutate(Min=min(F,M),
                   Max=max(F,M),
                   Diff=Max/Min-1) %>%
                arrange(desc(Diff)) %>%
                filter(Diff>.2)

right_label <- filter(right_label, City %in% big_diff$City)
left_label <- filter(left_label, City %in% big_diff$City)
highlight <-filter(city_gender,City %in% big_diff$City)
```


```{r}
ggplot(data = city_gender,aes(x=Revenue,y=City))+
  geom_line(aes(group=City),alpha = .3)+
  geom_point(aes(color=Gender),size=1.5,alpha = .3)+
  geom_line(data = highlight, aes(group = City)) +
  geom_point(data = highlight, aes(color = Gender), size = 2) +
  geom_text(data = right_label,aes(color=Gender,label=round(Revenue,0)),size=3,hjust=-.5)+
  geom_text(data = left_label,aes(color=Gender,label=round(Revenue,0)),size=3,hjust=1.5)+
  scale_x_continuous(limits = c(-500,10500))
```

#creating new plot label
```{r}
plot_label<- big_diff %>% select(City,Revenue=Max,Diff) %>%
            right_join(right_label)
```

```{r}
p<-ggplot(city_gender, aes(Revenue, City)) +
        geom_line(aes(group = City), alpha = .3) +
        geom_point(aes(color = Gender), size = 1.5, alpha = .3) +
        geom_line(data = highlight, aes(group = City)) +
        geom_point(data = highlight, aes(color = Gender), size = 2) +
        geom_text(data = plot_label, aes(color = Gender, 
                                         label = paste0("+", scales::percent(round(Diff, 2)))),
                  size = 3, hjust = -.5)
```


```{r}
library(extrafont)
pal2=c("tomato","green")
p + scale_color_discrete(labels = c("Female", "Male")) +
  # scale_color_manual(labels=paste("<span style='color:",
  #                                  pal2,
  #                                  "'>",
  #                                   unique(city_gender$Gender),
  #                                  "</span>"),values =pal2 )+
        scale_x_continuous(labels = scales::dollar, expand = c(0.02, 0), 
                           limits = c(0, 10500),
                           breaks = seq(0, 10000, by = 2500)) +
        scale_y_discrete(expand = c(.02, 0)) +
        labs(title = "Total Revenue by City and Gender",
             subtitle = "Out of 23 cities, eight locations experience a 20% or greater difference \nin revenue generated by males  versus females. Hidalgo experiences the \ngreatest difference with females generating 86% more revenue than males.") +
        theme_minimal() +
        theme(axis.title = element_blank(),
              panel.grid.major.x = element_blank(),
              panel.grid.minor = element_blank(),
              legend.title = element_blank(),
              legend.justification = c(0, 1), 
              legend.position = c(.1, 1.075),
              legend.background = element_blank(),
              legend.direction="horizontal",
              text = element_text(family = "Georgia"),
              plot.title = element_text(size = 20, margin = margin(b = 10)),
              plot.subtitle = element_text(size = 10, color = "darkslategrey", margin = margin(b = 25)),
              plot.caption = element_text(size = 8, margin = margin(t = 10), color = "grey70", hjust = 0))

ggsave("./cleveland.png")
```

